# Generated by Django 4.0.4 on 2022-07-03 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('rno', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.CharField(max_length=3)),
                ('income_status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('sclass', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('course_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=25)),
                ('fees', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student')], default=1, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='eccc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eccc_course', models.CharField(max_length=25)),
                ('no_of_seats', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('notification_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('info', models.CharField(max_length=50)),
                ('sender', models.CharField(max_length=25)),
                ('recieve', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=25)),
                ('dept', models.CharField(max_length=25)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Myapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='subjects',
            fields=[
                ('subject_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=50)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.classes')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.courses')),
            ],
        ),
        migrations.CreateModel(
            name='subject_handled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.staff')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='stud',
            fields=[
                ('rno', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('sclass', models.CharField(max_length=25)),
                ('section', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50)),
                ('DOB', models.DateField(default='1998-01-01')),
                ('academic_advisor', models.CharField(max_length=25)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('achievements', models.CharField(max_length=100)),
                ('scholarship', models.CharField(max_length=50)),
                ('fees', models.CharField(max_length=10)),
                ('midday_meal', models.CharField(max_length=20)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Myapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Myapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.CharField(max_length=3)),
                ('category', models.CharField(max_length=20)),
                ('rno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.stud')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('leave_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('purpose', models.CharField(max_length=100)),
                ('leave_date', models.DateField()),
                ('rno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.stud')),
            ],
        ),
        migrations.CreateModel(
            name='hod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Myapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=15)),
                ('class_held', models.CharField(max_length=3)),
                ('class_attended', models.CharField(max_length=3)),
                ('rno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.stud')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.subjects')),
            ],
        ),
    ]
